site_name: Silence's wiki
docs_dir: docs
nav:
  - Home: index.md
  - Pintos:
    - Lab2: pintos/pintos lab2 record.md 
  - ns3:
    - lsp: ns-3/ns3的lsp问题.md
theme: 
  name: 'material'
  langeage: 'zh'
  Palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light modeextra_css: 
  - stylesheets/extra.css
