site_name: Silence's wiki
docs_dir: docs
theme:  
  name: 'material'
  langeage: 'zh'
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: 'Switch to dark mode'
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: 'Switch to light mode' 
  font: false
nav:
  - Home: index.md
  - Pintos:
    - Lab2: pintos/pintos lab2 record.md 
  - ns3:
    - lsp: ns-3/ns3的奇妙问题.md
extra_css:
  - stylesheets/extra.css

